site_name: 'MeterSphere 文档'
site_url: 'https://metersphere.io'
site_description: 'Document'
site_author: 'wangzhen'
google_analytics: ['UA-147297392-7', 'metersphere.io']

repo_name: 'MeterSphere Docs'
repo_url: 'https://github.com/metersphere/metersphere'

edit_uri: https://github.com/metersphere/docs/edit/master/docs/
theme:
    name: 'material'
    logo: 'img/logo-white.png'
    favicon: 'img/facio.ico'
    language: 'zh'
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    custom_dir: 'theme'
nav:
    - 项目介绍: index.md
    - 快速开始: 
        - 一键部署: quick_start/quick_start.md
        - 创建项目: quick_start/create_project.md
        - 使用测试跟踪: quick_start/test_track.md
        - 使用接口测试: quick_start/api_test.md
        - 使用性能测试: quick_start/load_test.md
    - 系统架构: system_arch.md
    - 安装部署: 
        - 在线安装: installation/online_installation.md
        - 离线安装: installation/offline_installation.md
        - 在线升级: installation/online_upgrade.md
        - 离线升级: installation/offline_upgrade.md
    - 用户手册: 
        - 通用功能: user_manual/general.md
        - 系统设置: user_manual/system_management.md
        - 测试跟踪: user_manual/test_track.md
        # - 系统设置: 
        #     - 模块说明: user_manual/system_management/intro.md
        #     - 系统管理: user_manual/system_management/system.md
        #     - 组织管理: user_manual/system_management/organization.md
        #     - 工作空间管理: user_manual/system_management/workspace.md
        #     - 项目管理: user_manual/system_management/project.md
        #     - 个人信息管理: user_manual/system_management/personal.md
        # - 测试跟踪: 
        #     - 模块说明: user_manual/test_track/intro.md
        #     - 首页: user_manual/test_track/home.md
        #     - 测试用例: user_manual/test_track/test_case.md
        #     - 用例评审: user_manual/test_track/test_case_review.md
        #     - 测试计划: user_manual/test_track/test_plan.md
        #     - 报告: user_manual/test_track/test_report.md
        - 接口测试: 
            - 模块说明: user_manual/api_test/intro.md
            - 首页: user_manual/api_test/home.md
            - 接口定义: user_manual/api_test/api_definition.md
            - 接口自动化: user_manual/api_test/api_automation.md
            - 测试报告: user_manual/api_test/test_report.md
            - 用例步骤说明: user_manual/api_test/api_step.md
            # - 接口详情说明: user_manual/api_test/api_detail.md
            - 内置函数: user_manual/api_test/functions.md
        - 接口测试（旧版）: user_manual/api_test.md
        - 性能测试: user_manual/performance_test.md
        # - 性能测试:
        #     - 模块说明: user_manual/load_test/intro.md
        #     - 首页: user_manual/load_test/home.md
        #     - 性能测试: user_manual/load_test/api_definition.md
        #     - 测试报告: user_manual/load_test/test_report.md
    - 使用教程:
        - 使用 MeterSphere 进行 Dubbo 接口测试: tutorial/dubbo.md
        - 使用 MeterSphere 进行场景化接口测试: tutorial/api_testing.md
        - 使用预执行脚本功能生成接口认证签名: tutorial/pre_processor.md
        - 【视频】MeterSphere 如何与 TAPD和 Jira 对接: https://www.bilibili.com/video/BV1jr4y1c7Lg/
        - 【视频】MeterSphere 如何对接邮件、钉钉、企业微信: https://www.bilibili.com/video/BV1dp4y167ch/
        - 【视频】如何在 MeterSphere 中做场景化的接口测试: https://www.bilibili.com/video/BV1vy4y1q7f7/
        - 【视频】如何在 MeterSphere 中导入 Postman 脚本做接口测试: https://www.bilibili.com/video/BV1W54y1C7uY
        - 【视频】如何在 MeterSphere 中导入 Swagger UI 脚本做接口测试: https://www.bilibili.com/video/BV1YK411A7E8/
    - 常见问题:
        - 安装部署相关: faq/installation.md
        - 测试跟踪相关: faq/test_track.md
        - 接口测试相关: faq/api_test.md
        - 性能测试相关: faq/load_test.md
        - 系统设置相关: faq/system_management.md
        - 企业版相关: faq/enterprise.md
    - 开发文档: dev_manual.md
    - 用户案例: 
        - 88完美邮箱全面提升产品质量的落地指南: case_studies/88com.md
        - 蔚澜环保基于MeterSphere的自动化测试实践: case_studies/weilanep.md
        - 易盛信息MeterSphere接口测试使用经验: case_studies/esunny.md
    - 关于:
        - 更新说明: about/changelog.md
        - 联系我们: about/contact.md
    - JMeter 资源合集: awesome-jmeter.md
    - 企业版试用: enterprise.md

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: True
        linenums: False
    - toc:
        permalink: True
    - footnotes
    - attr_list
    - def_list
    - tables
    - abbr
    - md_in_html
    - pymdownx.extra
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.superfences
    - pymdownx.progressbar
    - lightgallery

extra_css:
    - css/extra.css

copyright: Copyright &copy; 2014-2020 <a href="https://www.fit2cloud.com">杭州飞致云信息科技有限公司</a>, All Rights Reserved. <a href="http://www.beian.miit.gov.cn" target="_blank">京ICP备15023818号</a>

plugins:
    - search

extra:
    version:
        method: mike